import type { NextPage, Metadata } from 'next'
import Image from 'next/image'

import { Navbar } from '../components'
import drop from '../assets/images/icons/drop.svg'
import clock from '../assets/images/icons/clock.svg'
import calendar from '../assets/images/icons/calendar.svg'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const Home: NextPage = () => {
  return (
    <>
      <header>
        <Navbar />
        <div className="intro w-100">
          <h1 className="fw-semibold display-2 px-3 px-md-0 mt-5">Lorem Ipsum Dolor Sit Amet</h1>
          <p className="fs-18 fw-semibold mx-auto mt-4 mb-5 px-3 px-md-0" style={{ maxWidth: '650px' }}>
            At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti
            atque corrupti.
          </p>
          <button type="button" className="btn btn-secondary rounded-pill fw-bold fs-5 px-5 py-3 mb-3">
            Schedule a Demo
          </button>
        </div>
        <div className="info container">
          <div className="info-element">
            <Image src={drop} alt="drop" />
            <span className="line" />
            <p className="justify-content-start">
              <span className="fs-1 fw-semibold pe-3">10%</span>
              <span>FUEL SAVINGS</span>
            </p>
          </div>
          <div className="info-element">
            <Image src={clock} alt="clock" />
            <span className="line" />
            <p>
              <span className="fs-1 fw-semibold">20%</span>
              <span>
                SAVINGS IN WORK
                <br />
                HOURS
              </span>
            </p>
          </div>
          <div className="info-element">
            <Image src={calendar} alt="calendar" />
            <span className="line" />
            <p>
              <span className="fs-1 fw-semibold">40%</span>
              <span>
                COST PRODUCTION
                <br />
                FROM ERROR DELAYS.
              </span>
            </p>
          </div>
        </div>
      </header>

      <main className="container-fluid pt-5">
        <p>
          Lorem ipsum, dolor sit amet consectetur adipisicing elit. Exercitationem iste omnis asperiores illo debitis
          rem cumque voluptatum illum, quo recusandae sapiente voluptatem nobis qui, officia error nam! Sunt,
          repudiandae nam.
        </p>
        <p>
          Lorem ipsum, dolor sit amet consectetur adipisicing elit. Exercitationem iste omnis asperiores illo debitis
          rem cumque voluptatum illum, quo recusandae sapiente voluptatem nobis qui, officia error nam! Sunt,
          repudiandae nam.
        </p>
        <p>
          Lorem ipsum, dolor sit amet consectetur adipisicing elit. Exercitationem iste omnis asperiores illo debitis
          rem cumque voluptatum illum, quo recusandae sapiente voluptatem nobis qui, officia error nam! Sunt,
          repudiandae nam.
        </p>
        <p>
          Lorem ipsum, dolor sit amet consectetur adipisicing elit. Exercitationem iste omnis asperiores illo debitis
          rem cumque voluptatum illum, quo recusandae sapiente voluptatem nobis qui, officia error nam! Sunt,
          repudiandae nam.
        </p>
        <p>
          Lorem ipsum, dolor sit amet consectetur adipisicing elit. Exercitationem iste omnis asperiores illo debitis
          rem cumque voluptatum illum, quo recusandae sapiente voluptatem nobis qui, officia error nam! Sunt,
          repudiandae nam.
        </p>
        <p>
          Lorem ipsum, dolor sit amet consectetur adipisicing elit. Exercitationem iste omnis asperiores illo debitis
          rem cumque voluptatum illum, quo recusandae sapiente voluptatem nobis qui, officia error nam! Sunt,
          repudiandae nam.
        </p>
        <p>
          Lorem ipsum, dolor sit amet consectetur adipisicing elit. Exercitationem iste omnis asperiores illo debitis
          rem cumque voluptatum illum, quo recusandae sapiente voluptatem nobis qui, officia error nam! Sunt,
          repudiandae nam.
        </p>
        <p>
          Lorem ipsum, dolor sit amet consectetur adipisicing elit. Exercitationem iste omnis asperiores illo debitis
          rem cumque voluptatum illum, quo recusandae sapiente voluptatem nobis qui, officia error nam! Sunt,
          repudiandae nam.
        </p>
        <p>
          Lorem ipsum, dolor sit amet consectetur adipisicing elit. Exercitationem iste omnis asperiores illo debitis
          rem cumque voluptatum illum, quo recusandae sapiente voluptatem nobis qui, officia error nam! Sunt,
          repudiandae nam.
        </p>
        <p>
          Lorem ipsum, dolor sit amet consectetur adipisicing elit. Exercitationem iste omnis asperiores illo debitis
          rem cumque voluptatum illum, quo recusandae sapiente voluptatem nobis qui, officia error nam! Sunt,
          repudiandae nam.
        </p>
        <p>
          Lorem ipsum, dolor sit amet consectetur adipisicing elit. Exercitationem iste omnis asperiores illo debitis
          rem cumque voluptatum illum, quo recusandae sapiente voluptatem nobis qui, officia error nam! Sunt,
          repudiandae nam.
        </p>
        <p>
          Lorem ipsum, dolor sit amet consectetur adipisicing elit. Exercitationem iste omnis asperiores illo debitis
          rem cumque voluptatum illum, quo recusandae sapiente voluptatem nobis qui, officia error nam! Sunt,
          repudiandae nam.
        </p>
        <p>
          Lorem ipsum, dolor sit amet consectetur adipisicing elit. Exercitationem iste omnis asperiores illo debitis
          rem cumque voluptatum illum, quo recusandae sapiente voluptatem nobis qui, officia error nam! Sunt,
          repudiandae nam.
        </p>
        <p>
          Lorem ipsum, dolor sit amet consectetur adipisicing elit. Exercitationem iste omnis asperiores illo debitis
          rem cumque voluptatum illum, quo recusandae sapiente voluptatem nobis qui, officia error nam! Sunt,
          repudiandae nam.
        </p>
        <p>
          Lorem ipsum, dolor sit amet consectetur adipisicing elit. Exercitationem iste omnis asperiores illo debitis
          rem cumque voluptatum illum, quo recusandae sapiente voluptatem nobis qui, officia error nam! Sunt,
          repudiandae nam.
        </p>
        <p>
          Lorem ipsum, dolor sit amet consectetur adipisicing elit. Exercitationem iste omnis asperiores illo debitis
          rem cumque voluptatum illum, quo recusandae sapiente voluptatem nobis qui, officia error nam! Sunt,
          repudiandae nam.
        </p>
        <p>
          Lorem ipsum, dolor sit amet consectetur adipisicing elit. Exercitationem iste omnis asperiores illo debitis
          rem cumque voluptatum illum, quo recusandae sapiente voluptatem nobis qui, officia error nam! Sunt,
          repudiandae nam.
        </p>
        <p>
          Lorem ipsum, dolor sit amet consectetur adipisicing elit. Exercitationem iste omnis asperiores illo debitis
          rem cumque voluptatum illum, quo recusandae sapiente voluptatem nobis qui, officia error nam! Sunt,
          repudiandae nam.
        </p>
        <p>
          Lorem ipsum, dolor sit amet consectetur adipisicing elit. Exercitationem iste omnis asperiores illo debitis
          rem cumque voluptatum illum, quo recusandae sapiente voluptatem nobis qui, officia error nam! Sunt,
          repudiandae nam.
        </p>
        <p>
          Lorem ipsum, dolor sit amet consectetur adipisicing elit. Exercitationem iste omnis asperiores illo debitis
          rem cumque voluptatum illum, quo recusandae sapiente voluptatem nobis qui, officia error nam! Sunt,
          repudiandae nam.
        </p>
        <p>
          Lorem ipsum, dolor sit amet consectetur adipisicing elit. Exercitationem iste omnis asperiores illo debitis
          rem cumque voluptatum illum, quo recusandae sapiente voluptatem nobis qui, officia error nam! Sunt,
          repudiandae nam.
        </p>
        <p>
          Lorem ipsum, dolor sit amet consectetur adipisicing elit. Exercitationem iste omnis asperiores illo debitis
          rem cumque voluptatum illum, quo recusandae sapiente voluptatem nobis qui, officia error nam! Sunt,
          repudiandae nam.
        </p>
        <p>
          Lorem ipsum, dolor sit amet consectetur adipisicing elit. Exercitationem iste omnis asperiores illo debitis
          rem cumque voluptatum illum, quo recusandae sapiente voluptatem nobis qui, officia error nam! Sunt,
          repudiandae nam.
        </p>
        <p>
          Lorem ipsum, dolor sit amet consectetur adipisicing elit. Exercitationem iste omnis asperiores illo debitis
          rem cumque voluptatum illum, quo recusandae sapiente voluptatem nobis qui, officia error nam! Sunt,
          repudiandae nam.
        </p>
        <p>
          Lorem ipsum, dolor sit amet consectetur adipisicing elit. Exercitationem iste omnis asperiores illo debitis
          rem cumque voluptatum illum, quo recusandae sapiente voluptatem nobis qui, officia error nam! Sunt,
          repudiandae nam.
        </p>
        <p>
          Lorem ipsum, dolor sit amet consectetur adipisicing elit. Exercitationem iste omnis asperiores illo debitis
          rem cumque voluptatum illum, quo recusandae sapiente voluptatem nobis qui, officia error nam! Sunt,
          repudiandae nam.
        </p>
        <p>
          Lorem ipsum, dolor sit amet consectetur adipisicing elit. Exercitationem iste omnis asperiores illo debitis
          rem cumque voluptatum illum, quo recusandae sapiente voluptatem nobis qui, officia error nam! Sunt,
          repudiandae nam.
        </p>
        <p>
          Lorem ipsum, dolor sit amet consectetur adipisicing elit. Exercitationem iste omnis asperiores illo debitis
          rem cumque voluptatum illum, quo recusandae sapiente voluptatem nobis qui, officia error nam! Sunt,
          repudiandae nam.
        </p>
        <p>
          Lorem ipsum, dolor sit amet consectetur adipisicing elit. Exercitationem iste omnis asperiores illo debitis
          rem cumque voluptatum illum, quo recusandae sapiente voluptatem nobis qui, officia error nam! Sunt,
          repudiandae nam.
        </p>
        <p>
          Lorem ipsum, dolor sit amet consectetur adipisicing elit. Exercitationem iste omnis asperiores illo debitis
          rem cumque voluptatum illum, quo recusandae sapiente voluptatem nobis qui, officia error nam! Sunt,
          repudiandae nam.
        </p>
        <p>
          Lorem ipsum, dolor sit amet consectetur adipisicing elit. Exercitationem iste omnis asperiores illo debitis
          rem cumque voluptatum illum, quo recusandae sapiente voluptatem nobis qui, officia error nam! Sunt,
          repudiandae nam.
        </p>
        <p>
          Lorem ipsum, dolor sit amet consectetur adipisicing elit. Exercitationem iste omnis asperiores illo debitis
          rem cumque voluptatum illum, quo recusandae sapiente voluptatem nobis qui, officia error nam! Sunt,
          repudiandae nam.
        </p>
        <p>
          Lorem ipsum, dolor sit amet consectetur adipisicing elit. Exercitationem iste omnis asperiores illo debitis
          rem cumque voluptatum illum, quo recusandae sapiente voluptatem nobis qui, officia error nam! Sunt,
          repudiandae nam.
        </p>
        <p>
          Lorem ipsum, dolor sit amet consectetur adipisicing elit. Exercitationem iste omnis asperiores illo debitis
          rem cumque voluptatum illum, quo recusandae sapiente voluptatem nobis qui, officia error nam! Sunt,
          repudiandae nam.
        </p>
        <p>
          Lorem ipsum, dolor sit amet consectetur adipisicing elit. Exercitationem iste omnis asperiores illo debitis
          rem cumque voluptatum illum, quo recusandae sapiente voluptatem nobis qui, officia error nam! Sunt,
          repudiandae nam.
        </p>
        <p>
          Lorem ipsum, dolor sit amet consectetur adipisicing elit. Exercitationem iste omnis asperiores illo debitis
          rem cumque voluptatum illum, quo recusandae sapiente voluptatem nobis qui, officia error nam! Sunt,
          repudiandae nam.
        </p>
        <p>
          Lorem ipsum, dolor sit amet consectetur adipisicing elit. Exercitationem iste omnis asperiores illo debitis
          rem cumque voluptatum illum, quo recusandae sapiente voluptatem nobis qui, officia error nam! Sunt,
          repudiandae nam.
        </p>
        <p>
          Lorem ipsum, dolor sit amet consectetur adipisicing elit. Exercitationem iste omnis asperiores illo debitis
          rem cumque voluptatum illum, quo recusandae sapiente voluptatem nobis qui, officia error nam! Sunt,
          repudiandae nam.
        </p>
        <p>
          Lorem ipsum, dolor sit amet consectetur adipisicing elit. Exercitationem iste omnis asperiores illo debitis
          rem cumque voluptatum illum, quo recusandae sapiente voluptatem nobis qui, officia error nam! Sunt,
          repudiandae nam.
        </p>
        <p>
          Lorem ipsum, dolor sit amet consectetur adipisicing elit. Exercitationem iste omnis asperiores illo debitis
          rem cumque voluptatum illum, quo recusandae sapiente voluptatem nobis qui, officia error nam! Sunt,
          repudiandae nam.
        </p>
      </main>
      <footer className="container-fluid">footer</footer>
    </>
  )
}

export default Home
