import type { NextPage, Metadata } from 'next'
import Image from 'next/image'

import { Navbar, Features, Plans } from '../components'
import drop from '../assets/images/icons/drop.svg'
import clock from '../assets/images/icons/clock.svg'
import calendar from '../assets/images/icons/calendar.svg'
import whoWeAreMain from '../assets/images/WhoWeAreMain.svg'
import purpose from '../assets/images/purpose.png'
import savings from '../assets/images/icons/savings.svg'
import visibility from '../assets/images/icons/visibility.svg'
import customer from '../assets/images/icons/customer.svg'
import error from '../assets/images/icons/error.svg'
import integration from '../assets/images/icons/integration.svg'
import banner from '../assets/images/banner.svg'
import fb from '../assets/images/icons/fb.svg'
import ins from '../assets/images/icons/ins.svg'
import x from '../assets/images/icons/x.svg'
import tel from '../assets/images/icons/tel.svg'

export const metadata: Metadata = {
  title: 'Hermes Logistic',
  description: 'Generated by create next app',
}

const Home: NextPage = () => {
  return (
    <>
      <header>
        <Navbar />
        <div className="intro w-100">
          <h1 className="fw-semibold display-2 px-3 px-md-0 mt-5">Lorem Ipsum Dolor Sit Amet</h1>
          <p className="fs-18 fw-semibold mx-auto mt-4 mb-5 px-3 px-md-0" style={{ maxWidth: '650px' }}>
            At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti
            atque corrupti.
          </p>
          <button type="button" className="btn btn-secondary rounded-pill fw-bold fs-5 px-5 py-3 mb-3">
            Schedule a Demo
          </button>
        </div>
        <div className="info container">
          <div className="info-element">
            <Image src={drop} alt="drop" width={30} height={30} />
            <span className="line" />
            <p className="justify-content-start">
              <span className="fs-1 fw-semibold pe-3">10%</span>
              <span>FUEL SAVINGS</span>
            </p>
          </div>
          <div className="info-element">
            <Image src={clock} alt="clock" width={30} height={30} />
            <span className="line" />
            <p>
              <span className="fs-1 fw-semibold">20%</span>
              <span>
                SAVINGS IN WORK
                <br />
                HOURS
              </span>
            </p>
          </div>
          <div className="info-element">
            <Image src={calendar} alt="calendar" width={30} height={30} />
            <span className="line" />
            <p>
              <span className="fs-1 fw-semibold">40%</span>
              <span>
                COST PRODUCTION
                <br />
                FROM ERROR DELAYS.
              </span>
            </p>
          </div>
        </div>
      </header>

      <main className="container-fluid px-0 pt-5">
        <section className="py-3 py-lg-5 d-flex justify-content-evenly align-items-center mw-1200">
          <div style={{ maxWidth: '510px' }}>
            <span className="fs-12 text-sunset fw-semibold">WHO WE ARE</span>
            <h2 className="display-5 fw-semibold lh-base py-4 mb-0">
              Title for this
              <br />
              Section Here
            </h2>
            <p className="fs-5">
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et
              dolore magna aliqua.
              <br />
              <br />
              Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
              consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla
              pariatur.
            </p>
          </div>
          <Image src={whoWeAreMain} alt="Who We Are" width={650} height={550} className="mw-100" />
        </section>

        <section>
          <ul id="CustomTabs" role="tablist">
            <li role="presentation">
              <button
                className="nav-link active"
                id="purpose-tab"
                data-bs-toggle="tab"
                data-bs-target="#purpose-tab-pane"
                type="button"
                role="tab"
                aria-controls="purpose-tab-pane"
                aria-selected="true"
                tabIndex={-1}
              >
                Our Purpose
              </button>
            </li>
            <li className="nav-item" role="presentation">
              <button
                className="nav-link"
                id="archive-tab"
                data-bs-toggle="tab"
                data-bs-target="#archive-tab-pane"
                type="button"
                role="tab"
                aria-controls="archive-tab-pane"
                aria-selected="false"
                tabIndex={-1}
              >
                What do we Want To Archive?
              </button>
            </li>
          </ul>
          <div className="tab-content" id="CustomTabsContent">
            <div
              className="tab-pane fade show active"
              id="purpose-tab-pane"
              role="tabpanel"
              aria-labelledby="purpose-tab"
              tabIndex={0}
            >
              <div className="tab-custom-content">
                <Image src={purpose} alt="Our purpose" width={550} className="mw-100" />
                <div style={{ maxWidth: '410px' }}>
                  <h2 className="display-5 fw-semibold lh-base pb-4 mb-0">Our Purpose</h2>
                  <p className="fs-5">
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore
                    et dolore magna aliqua.
                    <br />
                    <br />
                    Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
                    consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat
                    nulla pariatur.
                  </p>
                </div>
              </div>
            </div>
            <div
              className="tab-pane fade"
              id="archive-tab-pane"
              role="tabpanel"
              aria-labelledby="archive-tab"
              tabIndex={0}
            >
              <div className="tab-custom-content">
                <div style={{ maxWidth: '410px' }}>
                  <h2 className="display-5 fw-semibold pb-4 mb-0">What do we Want To Archive?</h2>
                  <p className="fs-5">
                    Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
                    consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat
                    nulla pariatur.
                  </p>
                </div>
                <Image src={purpose} alt="Our purpose" width={550} className="mw-100" />
              </div>
            </div>
          </div>
        </section>

        <section className="mw-1200 pt-5">
          <span className="fs-12 text-sunset fw-semibold">BENEFITS</span>
          <h2 className="display-5 fw-semibold pb-5 pt-4">Title for this Section Here</h2>

          <div className="benefits-grid fs-5">
            <div className="item">
              <Image src={savings} alt="Time and Money Savings" width={50} height={50} />
              <p>
                <span>Time and Money Savings</span>
                The route optimization offered by Hermes solution allows companies to save time and money in the process
                of delivering their products. By planning routes efficiently, drivers can deliver more products in less
                time, reducing operating costs and increasing efficiency.
              </p>
            </div>
            <div className="item">
              <Image src={visibility} alt="Increased Visibility and Control" width={50} height={50} />
              <p>
                <span>Increased Visibility and Control</span>
                Hermes solution provides complete visibility of the vehicle fleet, allowing companies to monitor the
                progress of deliveries and quickly respond to any issues or setbacks that arise. With Hermes solution,
                companies can have greater control over their delivery operations.
              </p>
            </div>
            <div className="item">
              <Image src={customer} alt="Improved Customer Satisfaction" width={50} height={50} />
              <p>
                <span>Improved Customer Satisfaction</span>
                With real-time monitoring and delivery to the correct areas thanks to geofencing, end customers receive
                their products on time, improving their satisfaction with the service and increasing customer loyalty.
              </p>
            </div>
            <div className="item">
              <Image src={error} alt="Error and Delay Reduction" width={50} height={50} />
              <p>
                <span>Error and Delay Reduction</span>
                The route optimization offered by Hermes solution allows companies to save time and money in the process
                of delivering their products. By planning routes efficiently, drivers can deliver more products in less
                time, reducing operating costs and increasing efficiency.
              </p>
            </div>
            <div className="item">
              <Image src={integration} alt="Easy integration with existing systems" width={50} height={50} />
              <p>
                <span>Easy integration with existing systems</span>
                Hermes solution offers complete visibility of the vehicle fleet, allowing companies to monitor delivery
                progress and respond quickly to any problems or setbacks that may arise. With Hermes solution, companies
                can have greater control over their delivery operations and easily integrate with their existing
                systems.
              </p>
            </div>
          </div>
        </section>

        <Features />

        <Plans />

        <section className="w-100 banner-section">
          <div className="banner">
            <div>
              <h2 className="display-5 fw-semibold">CTA title Banner Here</h2>
              <p className="fs-5 mb-4">
                Sed ut perspiciatis unde omnis iste natus error sit
                <br />
                voluptatem accusantium.
              </p>
              <button type="button" className="btn btn-secondary rounded-pill fs-5 fw-bold">
                CTA Text Here
              </button>
            </div>
            <Image src={banner} alt="Banner" width={440} height={565} />
          </div>
        </section>
      </main>
      <footer className="w-100">
        <div className="mw-1200">
          <div className="d-flex justify-content-between align-items-center pb-5">
            <Image src="/small-logo.svg" alt="Hermes Logistic" width={170} height={70} />
            <ul className="social">
              <li>
                <a href="http://google.com" target="_blank" rel="noopener noreferrer">
                  <Image src={fb} alt="Facebook" width={30} height={30} />
                </a>
              </li>
              <li>
                <a href="http://google.com" target="_blank" rel="noopener noreferrer">
                  <Image src={ins} alt="Instagram" width={30} height={30} />
                </a>
              </li>
              <li>
                <a href="http://google.com" target="_blank" rel="noopener noreferrer">
                  <Image src={x} alt="X" width={30} height={30} />
                </a>
              </li>
              <li>
                <a href="http://google.com" target="_blank" rel="noopener noreferrer">
                  <Image src={tel} alt="Telegram" width={30} height={30} />
                </a>
              </li>
            </ul>
          </div>

          <div className="terms">
            <span className="fs-12">©Hermes Company. All Rights Reserved</span>
            <a href="http://google.com" target="_blank" rel="noopener noreferrer" className="fs-12">
              Privacy Policy
            </a>
            <a href="http://google.com" target="_blank" rel="noopener noreferrer" className="fs-12">
              Terms & Conditions
            </a>
          </div>
        </div>
      </footer>
    </>
  )
}

export default Home
